spring:
  application:
    name: PdpTube
  datasource:
    #Buyerga hechkim tegmasin!
    url: jdbc:postgresql://dpg-cu9m8tpu0jms73fh0a3g-a.oregon-postgres.render.com:5432/wjmlvbcy_pdptube
    username: wjmlvbcy_pdptube_user
    password: wLfic44IBCEQ4nhMngyihFAeJg6nRzbO
      #url: jdbc:postgresql://localhost:5432/pdptube
      #username: postgres
      #password: root123
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  main:
    allow-bean-definition-overriding: true

jwt:
  secret-key: "753778214125442A472D4B6150645367566B59703373367639792F423F452848"
  expire-timeout: 36000000

server:
  servlet:
    context-path: /
